#!/usr/bin/env bash
# Run the full Customer Churn pipeline: train/evaluate/rank -> (optional UI).
# NOTE: data/customers.csv is the provided backend dataset — it is not
# regenerated by this script. See src/generate_data.py only if you want a
# fresh synthetic dataset instead.
set -euo pipefail
cd "$(dirname "$0")"

echo "== Training, evaluating, ranking =="
python -m src.train

echo
echo "Done. Artefacts in outputs/ and models/."
echo "Launch the dashboard with:  streamlit run app.py"
