#!/usr/bin/env bash
# Full Predictive Maintenance pipeline: label/feature/train/evaluate -> snapshot.
# NOTE: data/sensor_data.csv is the provided backend dataset — it is not
# regenerated by this script.
set -euo pipefail
cd "$(dirname "$0")"

echo "== Labelling, feature engineering, training, evaluation =="
python -m src.train

echo
echo "Done. Artefacts in outputs/ and models/."
echo "Launch the monitoring dashboard with:  streamlit run app.py"
