#!/usr/bin/env bash
# Full Product Recommendation pipeline: train/evaluate -> persist.
# NOTE: data/products.csv and data/interactions.csv are the provided backend
# dataset — they are not regenerated by this script.
set -euo pipefail
cd "$(dirname "$0")"

echo "== Training popularity / ALS / content / hybrid + evaluation =="
python -m src.train

echo
echo "Done. Artefacts in outputs/ and models/."
echo "Launch the API:   uvicorn api:app --reload --port 8000   (docs at /docs)"
echo "Launch the UI:    streamlit run app.py"
